name: Deploy Backend to Azure Container Apps

on:
  push:
    branches:
      - main  # Runs on push to the main branch

permissions:
  id-token: write  # Required for Azure OIDC authentication
  contents: read   # Needed to access repo content

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: "88b5e4a9-315d-4a05-9d68-915d53f723cb"
          tenant-id: "3e9340c6-1760-43f1-908c-c23ed3f4ba44"
          subscription-id: "7a1fc7a2-a2fd-4206-882c-c6fb039432bb"

      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name chargemateacr

      - name: Build and Push Docker Image
        run: |
          docker build -t chargemateacr.azurecr.io/simple-backend:latest .
          docker push chargemateacr.azurecr.io/simple-backend:latest

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name simple-backend \
            --resource-group chargeMate \
            --image chargemateacr.azurecr.io/simple-backend:latest
